# Generated by Django 4.1.7 on 2023-04-10 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRegitration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=200)),
                ('caMarks', models.CharField(max_length=200)),
                ('finalMarks', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ExaminationResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examTypes', models.CharField(choices=[('Test One', 'Test One'), ('Test Two', 'Test Two'), ('Final Exam', 'Final Exam')], max_length=200)),
                ('marks', models.CharField(max_length=200)),
                ('claim', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.courseregitration')),
                ('studentDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.student')),
            ],
        ),
    ]
