# Generated by Django 4.1.7 on 2023-04-10 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('durations', models.CharField(max_length=200)),
                ('semisterNo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=200)),
                ('registrtionNo', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.programreg')),
            ],
        ),
        migrations.CreateModel(
            name='CourseRegitration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=200)),
                ('caMarks', models.CharField(max_length=200)),
                ('finalMarks', models.CharField(max_length=200)),
                ('programName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.programreg')),
            ],
        ),
    ]
