# Generated by Django 4.1.7 on 2023-04-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_programreg_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programreg',
            name='type',
            field=models.CharField(choices=[('Bachelor Degree', 'Bachelor Degree'), ('DIPLOMA', 'DIPLOMA')], max_length=200),
        ),
    ]
